const animals = [
    {
        id:"deer",
        name:"Deer",
        type:"land",
        unlockedAt:0,
        power:0,
        hexes:[
            "forest",
            "pasture",
            "mountain",
            "spice"
        ],
        spawnRate:{
            initialChance:75,
            iterations:8
        },
        products:[
            "deer-hide",
            "venison"
        ]
    },
    {
        id:"humpback-whale",
        name:"Humpback Whale",
        type:"sea",
        unlockedAt:1,
        power:2,
        hexes:[
            "ocean",
            "harpoon"
        ],
        spawnRate:{
            initialChance:75,
            iterations:6
        },
        products:[
            "whale-skin",
            "whale-blubber"
        ]
    }, 
    {
        id:"leopard",
        name:"Leopard",
        type:"land",
        unlockedAt:2,
        power:3,
        hexes:[
            "mountain",
            "hills"
        ],
        spawnRate:{
            initialChance:49,
            iterations:6
        },
        products:[
            "leopard-skin"
        ]
    },
    {
        id:"ostrich",
        name:"Ostrich",
        type:"land",
        unlockedAt:3,
        power:1,
        hexes:[
            "forest",
            "pasture"
        ],
        spawnRate:{
            initialChance:79,
            iterations:6
        },
        products:[
            "ostrich-feather",
            "ostrich-egg"
        ]
    },
    {
        id:"dolphin",
        name:"Dolphin",
        type:"sea",
        unlockedAt:3,
        power:1,
        hexes:[
            "ocean",
            "harpoon"
        ],
        spawnRate:{
            initialChance:55,
            iterations:6
        },
        products:[
            "dolphin-brain"
        ]
    },
    {
        id:"crocodile",
        name:"Crocodile",
        type:"land",
        unlockedAt:4,
        power:1,
        hexes:[
            "forest",
            "swamp"
        ],
        spawnRate:{
            initialChance:68,
            iterations:7
        },
        products:[
            "croc-skin"
        ]
    },
    {
        id:"bear",
        name:"Bear",
        type:"land",
        unlockedAt:5,
        power:2,
        hexes:[
            "forest",
            "hills",
            "mountain",
            "spice"
        ],
        spawnRate:{
            initialChance:55,
            iterations:6
        },
        products:[
            "bear-pelt"
        ]
    },
    {
        id:"sperm-whale",
        name:"Sperm Whale",
        type:"sea",
        unlockedAt:5,
        power:2,
        hexes:[
            "ocean",
            "harpoon"
        ],
        spawnRate:{
            initialChance:51,
            iterations:5
        },
        products:[
            "whale-oil",
            "whale-oil",
            "whale-oil",
            "whale-blubber"
        ]
    },
    {
        id:"tiger",
        name:"Tiger",
        type:"land",
        unlockedAt:6,
        power:4,
        hexes:[
            "forest",
            "pasture",
            "gold",
            "spice"
        ],
        spawnRate:{
            initialChance:39,
            iterations:5
        },
        products:[
            "tiger-skin"
        ]
    },
    {
        id:"great-white-shark",
        name:"Great White Shark",
        type:"sea",
        unlockedAt:6,
        power:3,
        hexes:[
            "ocean",
            "harpoon"
        ],
        spawnRate:{
            initialChance:68,
            iterations:6
        },
        products:[
            "shark-teeth"
        ]
    },  
    {
        id:"narwhal",
        name:"Narwhal",
        type:"sea",
        unlockedAt:7,
        power:2,
        hexes:[
            "ocean",
            "harpoon"
        ],
        spawnRate:{
            initialChance:61,
            iterations:6
        },
        products:[
            "narwhal-horn"
        ]
    },
    {
        id:"rhino",
        name:"Rhino",
        type:"land",
        unlockedAt:8,
        power:4,
        hexes:[
            "desert",
            "pasture",
            "gold"
        ],
        spawnRate:{
            initialChance:41,
            iterations:5
        },
        products:[
            "rhino-horn"
        ]
    },
    {
        id:"lion",
        name:"Lion",
        type:"land",
        unlockedAt:9,
        power:5,
        hexes:[
            "desert",
            "pasture",
            "gold",
            "hills"
        ],
        spawnRate:{
            initialChance:34,
            iterations:5
        },
        products:[
            "lion-mane"
        ]
    },
    {
        id:"orca-whale",
        name:"Orca Whale",
        type:"sea",
        unlockedAt:9,
        power:4,
        hexes:[
            "ocean",
            "harpoon"
        ],
        spawnRate:{
            initialChance:51,
            iterations:5
        },
        products:[
            "orca-skin"
        ]
    },
    {
        id:"elephant",
        name:"Elephant",
        type:"land",
        unlockedAt:10,
        power:6,
        hexes:[
            "desert",
            "pasture",
            "gold",
            "forest",
            "spice"
        ],
        spawnRate:{
            initialChance:25,
            iterations:4
        },
        products:[
            "ivory"
        ]
    }
];