const resourceCards = [
    
    //alrighty. There's a crap ton of stuff, so here we go:
    //let's start with agriculture
    //more specifically, the fields hex
    /* TEMPLATE:
    {
        id:"",              //all lowercase
        name:"",            //display name 
        productType:"",     //premium, standard, base
        parent:"",          //null if base, otherwise parent display name
        parentId:"",        //same as above, except parent ID instead of DN
        hex:"",             //all lowercase
        expansion:"",       //expansion id, e.g.: AGR, IND, ND, "none"
        unlockedAt:0,       //AGR/IND tier that this is unlocked at
    } 
    */
    {
        id:"grain",
        name:"Grain",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"fields",
        expansion:"AGR",
        unlockedAt:0
    },
    {
        id:"wheat",
        name:"Wheat",
        productType:"standard",
        parent:"Grain",
        parentId:"grain",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:0
    },
    {
        id:"vegetable",
        name:"Vegetable",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"fields",
        expansion:"AGR",
        unlockedAt:1
    },
    {
        id:"carrot",
        name:"Carrot",
        productType:"standard",
        parent:"Vegetable",
        parentId:"vegetable",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:1
    },
    {
        id:"fruit",
        name:"Fruit",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"fields",
        expansion:"AGR",
        unlockedAt:2
    },
    {
        id:"tomato",
        name:"Tomato",
        productType:"standard",
        parent:"Fruit",
        parentId:"fruit",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:2
    },
    {
        id:"lettuce",
        name:"Lettuce",
        productType:"standard",
        parent:"Vegetable",
        parentId:"vegetable",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:3
    },
    {
        id:"rice",
        name:"Rice",
        productType:"standard",
        parent:"Grain",
        parentId:"grain",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:3
    },
    {
        id:"broccoli",
        name:"Broccoli",
        productType:"standard",
        parent:"Vegetable",
        parentId:"vegetable",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:4
    },
    {
        id:"cotton-sprig",
        name:"Cotton Sprig",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"fields",
        expansion:"AGR",
        unlockedAt:4
    },
    {
        id:"cotton",
        name:"Cotton",
        productType:"premium",
        parent:"Cotton Sprig",
        parentId:"cotton-sprig",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:4
    },
    {
        id:"beer",
        name:"Beer",
        productType:"premium",
        parent:"Grain",
        parentId:"grain",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:4
    },
    {
        id:"garlic",
        name:"Garlic",
        productType:"premium",
        parent:"Vegetable",
        parentId:"vegetable",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:5
    },
    {
        id:"apple",
        name:"Apple",
        productType:"standard",
        parent:"Fruit",
        parentId:"fruit",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:5
    },
    {
        id:"radish",
        name:"Radish",
        productType:"premium",
        parent:"Vegetable",
        parentId:"vegetable",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:6
    },
    {
        id:"oats",
        name:"Oats",
        productType:"premium",
        parent:"Grain",
        parentId:"grain",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:6
    },
    {
        id:"grape",
        name:"Grape",
        productType:"premium",
        parent:"Fruit",
        parentId:"fruit",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:7
    },
    
    {
        id:"banana",
        name:"Banana",
        productType:"premium",
        parent:"Fruit",
        parentId:"fruit",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:8
    },
    {
        id:"chili-pepper",
        name:"Chili Pepper",
        productType:"premium",
        parent:"Vegetable",
        parentId:"vegetable",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:9
    },
    {
        id:"cucumber",
        name:"Cucumber",
        productType:"premium",
        parent:"Vegetable",
        parentId:"vegetable",
        hex:"fields",
        expansion:"AGR",
        unlockedAt:10
    },
    
    //okay, fields is done. Let's do pasture now:

    {
        id:"sheep",
        name:"Sheep",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:0
    },
    {
        id:"wool",
        name:"Wool",
        productType:"standard",
        parent:"Sheep",
        parentId:"sheep",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:0
    },
    {
        id:"cow",
        name:"Cow",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:1
    },
    {
        id:"cloth",
        name:"Cloth",
        productType:"premium",
        parent:"Sheep",
        parentId:"sheep",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:1
    },
    {
        id:"lamb-chop",
        name:"Lamb Chop",
        productType:"standard",
        parent:"Sheep",
        parentId:"sheep",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:2
    },
    {
        id:"milk",
        name:"Milk",
        productType:"standard",
        parent:"Cow",
        parentId:"cow",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:2
    },
    {
        id:"chicken",
        name:"Chicken",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:3
    },
    {
        id:"leather",
        name:"Leather",
        productType:"standard",
        parent:"Cow",
        parentId:"cow",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:3
    },
    {
        id:"egg",
        name:"Egg",
        productType:"standard",
        parent:"Chicken",
        parentId:"chicken",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:4
    },
    {
        id:"beef",
        name:"Beef",
        productType:"standard",
        parent:"Cow",
        parentId:"cow",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:4
    },
    {
        id:"pig",
        name:"Pig",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:5
    },
    {
        id:"drumstick",
        name:"Drumstick",
        productType:"premium",
        parent:"Chicken",
        parentId:"chicken",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:5
    },
    {
        id:"pork",
        name:"Pork",
        productType:"standard",
        parent:"Pig",
        parentId:"pig",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:6
    },
    {
        id:"cow-tongue",
        name:"Cow Tongue",
        productType:"premium",
        parent:"Cow",
        parentId:"cow",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:6
    },
    {
        id:"goat",
        name:"Goat",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:7
    },
    {
        id:"feather",
        name:"Feather",
        productType:"premium",
        parent:"Chicken",
        parentId:"chicken",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:8
    },
    {
        id:"bacon",
        name:"Bacon",
        productType:"premium",
        parent:"Pig",
        parentId:"pig",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:9
    },
    {
        id:"goat-cheese",
        name:"Goat Cheese",
        productType:"premium",
        parent:"Goat",
        parentId:"goat",
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:10
    },
    {
        id:"horse",
        name:"Horse",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"pasture",
        expansion:"AGR",
        unlockedAt:11
    },

    //okay, next in AGR is spice
    //fortunately there aren't a whole lot of spice cards

    {
        id:"spice",
        name:"Spice",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"spice",
        expansion:"AGR",
        unlockedAt:0
    },
    {
        id:"nutmeg",
        name:"Nutmeg",
        productType:"premium",
        parent:"Spice",
        parentId:"spice",
        hex:"spice",
        expansion:"AGR",
        unlockedAt:0
    },
    {
        id:"cinnamon",
        name:"Cinnamon",
        productType:"premium",
        parent:"Spice",
        parentId:"spice",
        hex:"spice",
        expansion:"AGR",
        unlockedAt:2
    },
    {
        id:"sugar-cane",
        name:"Sugar Cane",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"spice",
        expansion:"AGR",
        unlockedAt:3
    },
    {
        id:"sugar",
        name:"Sugar",
        productType:"premium",
        parent:"Sugar Cane",
        parentId:"sugar-cane",
        hex:"spice",
        expansion:"AGR",
        unlockedAt:3
    },
    {
        id:"pepper",
        name:"Pepper",
        productType:"premium",
        parent:"Spice",
        parentId:"spice",
        hex:"spice",
        expansion:"AGR",
        unlockedAt:4
    },
    {
        id:"tobacco",
        name:"Tobacco",
        productType:"premium",
        parent:"Spice",
        parentId:"spice",
        hex:"spice",
        expansion:"AGR",
        unlockedAt:6
    },
    {
        id:"rosemary",
        name:"Rosemary",
        productType:"premium",
        parent:"Spice",
        parentId:"spice",
        hex:"spice",
        expansion:"AGR",
        unlockedAt:6
    },

    //SPICES are done
    //that completes AGR
    //moving on to IND, forest:

    {
        id:"lumber",
        name:"Lumber",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"forest",
        expansion:"IND",
        unlockedAt:0
    },
    {
        id:"wood",
        name:"Wood",
        productType:"standard",
        parent:"Lumber",
        parentId:"lumber",
        hex:"forest",
        expansion:"IND",
        unlockedAt:0
    },
    {
        id:"paper",
        name:"Paper",
        productType:"premium",
        parent:"Lumber",
        parentId:"lumber",
        hex:"forest",
        expansion:"IND",
        unlockedAt:0
    },
    {
        id:"timber",
        name:"Timber",
        productType:"standard",
        parent:"Lumber",
        parentId:"lumber",
        hex:"forest",
        expansion:"IND",
        unlockedAt:2
    },
    {
        id:"charcoal",
        name:"Charcoal",
        productType:"standard",
        parent:"Lumber",
        parentId:"lumber",
        hex:"forest",
        expansion:"IND",
        unlockedAt:3
    },
    {
        id:"fiber",
        name:"Fiber",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"forest",
        expansion:"IND",
        unlockedAt:5
    },
    {
        id:"thread",
        name:"Thread",
        productType:"standard",
        parent:"Fiber",
        parentId:"fiber",
        hex:"forest",
        expansion:"IND",
        unlockedAt:6
    },
    {
        id:"maple",
        name:"Maple",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"forest",
        expansion:"IND",
        unlockedAt:7
    },
    {
        id:"maple-syrup",
        name:"Maple Syrup",
        productType:"premium",
        parent:"Maple",
        parentId:"maple",
        hex:"forest",
        expansion:"IND",
        unlockedAt:8
    },
    {
        id:"silk",
        name:"Silk",
        productType:"premium",
        parent:"Fiber",
        parentId:"fiber",
        hex:"forest",
        expansion:"IND",
        unlockedAt:9
    },
    {
        id:"acacia-wood",
        name:"Acacia Wood",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"forest",
        expansion:"IND",
        unlockedAt:10
    },
    {
        id:"acacia-plank",
        name:"Acacia Plank",
        productType:"premium",
        parent:"Acacia Wood",
        parentId:"acacia-wood",
        hex:"forest",
        expansion:"IND",
        unlockedAt:10
    },

    //forest is done, next is hills

    {
        id:"clay",
        name:"Clay",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"hills",
        expansion:"IND",
        unlockedAt:0
    },
    {
        id:"brick",
        name:"Brick",
        productType:"standard",
        parent:"Clay",
        parentId:"clay",
        hex:"hills",
        expansion:"IND",
        unlockedAt:0
    },
    {
        id:"stone",
        name:"Stone",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"hills",
        expansion:"IND",
        unlockedAt:1
    },
    {
        id:"cobblestone",
        name:"Cobblestone",
        productType:"standard",
        parent:"Stone",
        parentId:"stone",
        hex:"hills",
        expansion:"IND",
        unlockedAt:1
    },
    {
        id:"pottery",
        name:"Pottery",
        productType:"premium",
        parent:"Clay",
        parentId:"clay",
        hex:"hills",
        expansion:"IND",
        unlockedAt:2
    },
    {
        id:"mineral-chunk",
        name:"Mineral Chunk",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"hills",
        expansion:"IND",
        unlockedAt:4
    },
    {
        id:"salt",
        name:"Salt",
        productType:"premium",
        parent:"Mineral Chunk",
        parentId:"mineral-chunk",
        hex:"hills",
        expansion:"IND",
        unlockedAt:5
    },
    {
        id:"tile",
        name:"Tile",
        productType:"standard",
        parent:"Clay",
        parentId:"clay",
        hex:"hills",
        expansion:"IND",
        unlockedAt:6
    },
    {
        id:"sulfur",
        name:"Sulfur",
        productType:"standard",
        parent:"Mineral Chunk",
        parentId:"mineral-chunk",
        hex:"hills",
        expansion:"IND",
        unlockedAt:7
    },
    {
        id:"amber",
        name:"Amber",
        productType:"premium",
        parent:"Mineral Chunk",
        parentId:"mineral-chunk",
        hex:"hills",
        expansion:"IND",
        unlockedAt:9
    },
    //hills is done, mountain is last!
    
    {
        id:"ore",
        name:"Ore",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"mountain",
        expansion:"IND",
        unlockedAt:0
    },
    {
        id:"iron-ingot",
        name:"Iron Ingot",
        productType:"standard",
        parent:"Ore",
        parentId:"ore",
        hex:"mountain",
        expansion:"IND",
        unlockedAt:0
    },
    {
        id:"coins",
        name:"Coins",
        productType:"premium",
        parent:"Ore",
        parentId:"ore",
        hex:"mountain",
        expansion:"IND",
        unlockedAt:1
    },
    {
        id:"steel-ingot",
        name:"Steel Ingot",
        productType:"standard",
        parent:"Ore",
        parentId:"ore",
        hex:"mountain",
        expansion:"IND",
        unlockedAt:3
    },
    {
        id:"gemstone",
        name:"Gemstone",
        productType:"base",
        parent:null,
        parentId:null,
        hex:"mountain",
        expansion:"IND",
        unlockedAt:6
    },
    {
        id:"silver-ingot",
        name:"Silver Ingot",
        productType:"premium",
        parent:"Ore",
        parentId:"ore",
        hex:"mountain",
        expansion:"IND",
        unlockedAt:7
    },
    {
        id:"emerald",
        name:"Emerald",
        productType:"premium",
        parent:"Gemstone",
        parentId:"gemstone",
        hex:"mountain",
        expansion:"IND",
        unlockedAt:8
    },
    {
        id:"gold-ingot",
        name:"Gold Ingot",
        productType:"premium",
        parent:"Ore",
        parentId:"ore",
        hex:"mountain",
        expansion:"IND",
        unlockedAt:9
    },
    {
        id:"diamond",
        name:"Diamond",
        productType:"premium",
        parent:"Gemstone",
        parentId:"gemstone",
        hex:"mountain",
        expansion:"IND",
        unlockedAt:10
    },

    //ash
    {
        id:"ash",
        name:"Ash",
        productType:"premium",
        parent:null,
        parentId:null,
        hex:"volcano",
        expansion:"ND",
        unlockedAt:0
    },

    // wilderness
    {
        id:"orca-skin",
        name:"Orca Skin",
        productType:"premium",
        parent:null,
        parentId:null,
        hex:"ocean",
        expansion:"WILD",
        unlockedAt:0
    },
    {
        id:"narwhal-horn",
        name:"Narwhal Horn",
        productType:"premium",
        parent:null,
        parentId:null,
        hex:"ocean",
        expansion:"WILD",
        unlockedAt:0
    },
    {
        id:"dolphin-brain",
        name:"Dolphin Brain",
        productType:"premium",
        parent:null,
        parentId:null,
        hex:"ocean",
        expansion:"WILD",
        unlockedAt:0
    },
    {
        id:"whale-oil",
        name:"Whale Oil",
        productType:"premium",
        parent:null,
        parentId:null,
        hex:"ocean",
        expansion:"WILD",
        unlockedAt:0
    },
    {
        id:"whale-blubber",
        name:"Whale Blubber",
        productType:"premium",
        parent:null,
        parentId:null,
        hex:"ocean",
        expansion:"WILD",
        unlockedAt:0
    },
    {
        id:"whale-skin",
        name:"Whale Skin",
        productType:"premium",
        parent:null,
        parentId:null,
        hex:"ocean",
        expansion:"WILD",
        unlockedAt:0
    },
    {
        id:"shark-teeth",
        name:"Shark Teeth",
        productType:"premium",
        parent:null,
        parentId:null,
        hex:"ocean",
        expansion:"WILD",
        unlockedAt:0
    },

    {
        id:"croc-skin",
        name:"Croc Skin",
        productType:"premium",
        parent:null,
        parentId:null,
        hex:null,
        expansion:"WILD",
        unlockedAt:0
    },
];